apiVersion: v1
kind: Service
metadata:
  name: gemini-sample-frontend
  labels:
    app: gemini-sample-frontend
spec:
  type: NodePort
  selector:
    app: gemini-sample-frontend
  ports:
    - name: http
      port: 3000
      targetPort: 3000
      nodePort: 30080
